// Lightweight UI smoke against the isolated synthetic preview. Uses local Chrome.
// Supply INVOICELENS_PLAYWRIGHT as an existing Playwright module path if it is
// not installed normally. This script never downloads a browser or dependencies.
import fs from 'node:fs/promises'
import path from 'node:path'
import assert from 'node:assert/strict'
import { fileURLToPath, pathToFileURL } from 'node:url'

const project = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const { chromium } = await import(process.env.INVOICELENS_PLAYWRIGHT ? pathToFileURL(process.env.INVOICELENS_PLAYWRIGHT).href : 'playwright')
const base = process.env.INVOICELENS_PREVIEW_URL || 'http://127.0.0.1:4312'
const evidence = path.join(project, process.env.INVOICELENS_QA_DIR || 'docs/screenshots/regression-2026-10-06')
await fs.mkdir(evidence, { recursive: true })
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' })
const page = await context.newPage()
const failures = []
const completed = []
let outcome = 'failed'
let qaFailure = null
page.on('pageerror', (error) => failures.push(error.message))
const screenshot = (name) => page.screenshot({ path: path.join(evidence, name + '.png'), fullPage: false })
const route = async (name) => { await page.goto(base + '/#/' + name); await page.locator('main').waitFor() }
const step = async (label, run) => { await run(); completed.push(label); console.log('PASS ' + label) }
try {
  await step('DEMO-aware login and invalid credentials recover', async () => {
    await page.goto(base)
    await page.getByRole('button', { name: 'Use demo operator' }).click()
    await page.getByLabel('Password', { exact: true }).fill('invalid-password')
    await page.getByRole('button', { name: 'Enter workbench' }).click()
    await page.getByRole('alert').waitFor()
    await screenshot('01-login')
    await page.getByRole('button', { name: 'Use demo operator' }).click()
    await page.getByRole('button', { name: 'Enter workbench' }).click()
    await page.locator('.operations-hero h1').waitFor()
    await screenshot('02-overview-desktop')
  })
  await step('client rejection, native intake and server deduplication', async () => {
    await route('intake')
    const input = page.locator('input[type=file]')
    await input.setInputFiles({ name: 'unsupported.txt', mimeType: 'text/plain', buffer: Buffer.from('not a document') })
    await page.getByRole('alert').filter({ hasText: 'not a PDF' }).waitFor()
    const invoice = path.join(project, 'generated/invoicelens-fast/documents/INV-0004.pdf')
    await input.setInputFiles(invoice)
    await input.setInputFiles(invoice)
    assert.equal(await page.locator('.selected-file').count(), 1)
    await page.getByRole('button', { name: 'Start processing' }).click()
    await page.locator('.upload-results').waitFor()
    await input.setInputFiles(invoice)
    await page.getByRole('button', { name: 'Start processing' }).click()
    await page.getByText('Already in workspace', { exact: true }).waitFor()
    await screenshot('03-intake-repeat')
    await input.setInputFiles({ name: 'damaged.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.7 damaged synthetic test') })
    await page.getByRole('button', { name: 'Start processing' }).click()
    await page.locator('.upload-results').filter({ hasText: 'Rejected' }).waitFor()
    await screenshot('04-intake-rejected')
  })
  await step('global search, empty filter, clear and stage navigation', async () => {
    await route('queue?status=all')
    await page.locator('.queue-item').first().waitFor()
    await page.getByLabel('Filter queue', { exact: true }).fill('no-match-synthetic-zz')
    await page.getByRole('heading', { name: 'No documents match these filters' }).waitFor()
    await page.getByRole('button', { name: 'View all documents', exact: true }).click()
    assert.equal(await page.getByLabel('Filter queue', { exact: true }).inputValue(), '')
    await page.getByLabel('Search documents', { exact: true }).fill('HI-PO-00001')
    await page.getByLabel('Search documents', { exact: true }).press('Enter')
    await page.locator('.queue-item').filter({ hasText: 'HI-PO-00001' }).waitFor()
    await page.getByRole('button', { name: 'Clear search', exact: true }).click()
    await page.getByLabel('Document type').selectOption('purchase_order')
    await page.getByLabel('Sort by').selectOption('vendor')
    await screenshot('05-queue-desktop')
  })
  await step('profile apply, reload, invalid import, export and reset', async () => {
    await route('settings')
    await page.getByLabel('Product name', { exact: true }).fill('Northstar Desk')
    await page.getByLabel('Workspace display name', { exact: true }).fill('Northstar · Synthetic pilot')
    await page.getByRole('radio', { name: 'Teal', exact: true }).check()
    await page.getByLabel('Queue density').selectOption('compact')
    await page.getByLabel('Default queue view').selectOption('all')
    await page.getByRole('button', { name: 'Apply changes' }).click()
    await page.getByRole('status').filter({ hasText: 'Profile saved' }).waitFor()
    await page.reload()
    await page.getByLabel('Product name', { exact: true }).waitFor()
    assert.equal(await page.getByLabel('Product name', { exact: true }).inputValue(), 'Northstar Desk')
    const downloadEvent = page.waitForEvent('download')
    await page.getByRole('button', { name: 'Export applied profile' }).click()
    const download = await downloadEvent
    const profileFile = path.join(project, 'tmp/qa-applied-profile.json')
    await download.saveAs(profileFile)
    assert.equal(JSON.parse(await fs.readFile(profileFile, 'utf8')).accent, 'teal')
    const input = page.getByLabel('Import workspace profile', { exact: true })
    await input.setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{invalid') })
    await page.getByRole('alert').filter({ hasText: 'not valid JSON' }).waitFor()
    assert.equal(await page.getByLabel('Product name', { exact: true }).inputValue(), 'Northstar Desk')
    await input.setInputFiles(profileFile)
    await page.getByRole('status').filter({ hasText: 'Profile loaded' }).waitFor()
    await page.getByRole('button', { name: 'Apply changes' }).click()
    await screenshot('06-profile-desktop')
    await page.getByRole('button', { name: 'Reset appearance' }).click()
    assert.equal(await page.getByLabel('Product name', { exact: true }).inputValue(), 'InvoiceLens')
  })
  await step('source evidence, keyboard tabs, version approval and repeated XLSX', async () => {
    await route('queue?status=all')
    await page.locator('.queue-item').filter({ hasText: 'HI-PO-00001' }).click()
    await page.getByRole('region', { name: 'Structured data and review' }).waitFor()
    await page.locator('.source-image-frame img').waitFor()
    await page.getByRole('tab', { name: 'Details', exact: true }).click()
    await page.locator('.field-select').filter({ hasText: 'Subtotal' }).click()
    await page.getByRole('tab', { name: 'Details' }).focus()
    await page.keyboard.press('ArrowRight')
    assert.equal(await page.getByRole('tab', { name: /^Findings/ }).getAttribute('aria-selected'), 'true')
    await page.keyboard.press('Home')
    await screenshot('07-review-desktop')
    const approve = page.getByRole('button', { name: /^Approve v/ })
    if (await approve.count()) { await approve.click() }
    await page.getByRole('button', { name: 'Download XLSX', exact: true }).waitFor()
    for (let index = 0; index < 2; index++) {
      const event = page.waitForEvent('download')
      await page.getByRole('button', { name: 'Download XLSX', exact: true }).click()
      const download = await event
      const file = path.join(project, 'tmp/qa-approved-' + index + '.xlsx')
      await download.saveAs(file)
      assert.equal((await fs.readFile(file)).subarray(0, 2).toString(), 'PK')
    }
    await page.getByRole('button', { name: 'Edit Issue date', exact: true }).click()
    const correctedDate = page.getByLabel('Correct value', { exact: true })
    await correctedDate.fill(await correctedDate.inputValue() === '2026-10-01' ? '2026-10-02' : '2026-10-01')
    await page.getByLabel('Reason for correction').fill('Synthetic local QA: verify versioned correction and reapproval')
    await page.getByRole('button', { name: 'Save & revalidate', exact: true }).click()
    await page.getByRole('button', { name: /^Approve v/ }).waitFor()
    assert.equal(await page.getByRole('button', { name: 'Download XLSX', exact: true }).count(), 0)
    await page.getByRole('button', { name: /^Approve v/ }).click()
    await page.getByRole('button', { name: 'Download XLSX', exact: true }).waitFor()
    await screenshot('13-corrected-reapproved')
  })
  await step('390px mobile navigation, source switching and no horizontal overflow', async () => {
    await page.setViewportSize({ width: 390, height: 844 })
    await route('overview')
    await page.locator('.operations-hero h1').waitFor()
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true)
    await screenshot('08-overview-mobile')
    await page.getByRole('button', { name: 'Open menu', exact: true }).click()
    await page.getByRole('dialog', { name: 'Workspace navigation' }).waitFor()
    await page.keyboard.press('Escape')
    assert.equal(await page.getByRole('button', { name: 'Open menu', exact: true }).getAttribute('aria-expanded'), 'false')
    await route('queue?status=all')
    await page.locator('.queue-item').filter({ hasText: 'HI-PO-00001' }).click()
    await page.getByRole('button', { name: 'Details', exact: true }).waitFor()
    assert.equal(await page.locator('.source-panel').isVisible(), false)
    await page.getByRole('tab', { name: 'Details', exact: true }).click()
    await screenshot('09-review-mobile-record')
    await page.locator('.field-select').filter({ hasText: 'Subtotal' }).click()
    assert.equal(await page.getByRole('button', { name: 'Document', exact: true }).getAttribute('aria-pressed'), 'true')
    await page.locator('.source-image-frame img').waitFor()
    assert.equal(await page.locator('.data-scroll').isVisible(), false)
    assert.equal(await page.locator('.data-footer').isVisible(), true)
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true)
    await screenshot('10-review-mobile-source')
    await route('settings')
    await page.getByLabel('Product name', { exact: true }).waitFor()
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true)
    await screenshot('11-profile-mobile')
    await route('queue?status=failed')
    await page.getByRole('heading', { name: 'No documents in this stage' }).waitFor()
    await screenshot('12-empty-queue-mobile')
  })
  await step('injected API error recovers on retry', async () => {
    await page.route('**/api/documents', (route) => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ detail: 'Synthetic QA outage. Retry when the local API returns.' }) }))
    await route('queue?status=all')
    await page.reload()
    await page.getByRole('heading', { name: 'Unable to load this view' }).waitFor()
    await screenshot('14-api-error-mobile')
    await page.unroute('**/api/documents')
    await page.getByRole('button', { name: 'Retry', exact: true }).click()
    await page.locator('.queue-item').first().waitFor()
  })
  assert.deepEqual(failures, [], 'Unexpected JavaScript page errors')
  outcome = 'passed'
} catch (error) {
  qaFailure = error.message
  await screenshot('failure-state')
  throw error
} finally {
  await fs.writeFile(path.join(evidence, 'qa-result.json'), JSON.stringify({ base, browser: 'user local Chrome, isolated headless session', outcome, completed, pageErrors: failures, qaFailure, finishedAt: new Date().toISOString() }, null, 2))
  await browser.close()
}
